### ISSUE TITLE
Chrome complaining about missing subject alt name

### ISSUE THREAD

**Issue by developit** [davewasmer/devcert#1]
It seems like a recent update to Chrome enforces that self-signed certificates be generated with an alt name in addition to just a common name.

See related SO comment: https://stackoverflow.com/questions/43665243/chrome-invalid-self-signed-ssl-cert-subject-alternative-name-missing

Screenshot of the issue on Windows:
![image](https://user-images.githubusercontent.com/105127/27016539-1d2459ac-4eef-11e7-9e29-b0cb2704cc22.png)

**Comment by davewasmer** [comment]
This should be fixed on the recent refactor on master now.
