### ISSUE TITLE
NET::ERR_CERT_DATE_INVALID

### ISSUE THREAD

**Issue by pruett** [davewasmer/devcert#25]
I'm getting a `NET::ERR_CERT_DATE_INVALID` when generating tokens in the following manner. Is there anything that jumps out here that's invalid?

```js
const host = "my-app.test";

const handleCerts = async () => {
    const certsDir = path.resolve(__dirname, "certs");
    const { key, cert } = await certificateFor(host);

    if (!fs.existsSync(certsDir)) {
        fs.mkdirSync(certsDir);
    }

    fs.writeFileSync(`${certsDir}/ssl.key`, key);
    fs.writeFileSync(`${certsDir}/ssl.cert`, cert);
    return;
};

handleCerts().then(() => {/*kick off server*/}
```

edit:

```
Subject: my-app.test

Issuer: devcert

Expires on: Sep 17, 2037

Current date: Jul 19, 2018
```

**Comment by pruett** [comment]
Hm, this is odd because this works on my machine at home but fails at my work computer. I wonder if there are certain restrictions at the network at work that's causing these errors. In addition to the error above, I'm also getting errors when trying to create certs for domains ending in `.dev` for example.

I'm assuming this is an isolated VPN issue. I'll try investigating further

**Comment by pruett** [comment]
this appeared to be an isolated network issue.

**Comment by natew** [comment]
I'm getting this issue now, though not sure exactly what caused it. But I've verified it on three wifi networks, with and without a VPN. Any clues for debugging? The expiration seems valid:

```
Your connection is not private
Attackers might be trying to steal your information from orbitauth.com (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_DATE_INVALID
Subject: myauth.com

Issuer: devcert

Expires on: Jan 25, 2038

Current date: Jan 16, 2019
```

**Comment by natew** [comment]
Oh safari gives a better idea:

![image](https://user-images.githubusercontent.com/12100/51275969-424b7980-1988-11e9-9117-af1c1b073c4b.png)

**Comment by natew** [comment]
Ok, deleting the entire `~/Library/Application Support/devcert` fixed it. Before I was trying to clear individual sub-files.
