### ISSUE TITLE
Feature: Provide api to flush specific cert

### ISSUE THREAD

**Issue by jimthedev** [davewasmer/devcert#3]
It would be great to be able to flush a specific cert. I could delete the entire ~/.config/devcert directory but would prefer to go through a more official channel so as not to impact anything other than the cert I am interested in flushing.

**Comment by davewasmer** [comment]
Great idea. PR's welcome on this! I'll try to tackle it after the recent refactor that has just landed on master gets published.

**Comment by jimthedev** [comment]
Thanks. Incoming baby so it might be a while but I will keep it in my todo list.

**Comment by davewasmer** [comment]
I know the feeling, so no worries :wink:

Congrats and good luck!

**Comment by davewasmer** [comment]
@jimthedev hope all is well with the new arrival!

The `removeDomain` API should solve this. I'm closing the issue for now, but if it's lacking in some respect, please feel free to drop a note and I'll reopen.
