### ISSUE TITLE
localhost is not a valid domain name

### ISSUE THREAD

**Issue by stramel** [davewasmer/devcert#56]
On the latest version (using `devcert-cli`):

```
devcert generate localhost
Error: "localhost" is not a valid domain name.
```

same for `127.0.0.1` and my local ip

**Comment by Js-Brecht** [comment]
v1.1.1?

**Comment by stramel** [comment]
@Js-Brecht I believe so, I did a fresh install on my mac using `npm I -g devcert-cli` and it didn't work. Used the previously installed version on my Windows machine and it worked. 

I checked the Regex in the diff for 1.1.1 and it doesn't match for any of the ones I tried.

**Comment by Js-Brecht** [comment]
What package manager are you using?  You should be able to use it to query your dependency tree.  Something like `yarn why devcert`, `npm ls devcert`, or `pnpm ls --filter devcert`.

I’m just trying to figure out what version you’re on because an update was published today that would probably cause the problem you’re experiencing

**Comment by Js-Brecht** [comment]
Oh, I see now you’re using npm.  I overlooked that before

**Comment by leeuwd** [comment]
Same here

![image](https://user-images.githubusercontent.com/1755190/84512039-b1391900-acc7-11ea-8cd0-a876abe62d88.png)

Gatsby breaks too: https://www.gatsbyjs.org/docs/local-https/

**Comment by Js-Brecht** [comment]
The RegExp is here:
https://github.com/davewasmer/devcert/blob/d979a93e61a26f8e67ca7b6a86798aca82214aa6/src/constants.ts#L9

I've been really swamped lately, so I don't know when I'll have time to work on that regular expression.  It should support IP addresses & single DC (e.g. localhost), but it should also still restrict the domain to valid inputs.

**Comment by JustFly1984** [comment]
In `Gatsby.js`, pinning `devcert` to `1.1.0` fixes issues on MaxOS, but causes issues with ubuntu 18 in Github Actions. Errors are the same for both versions: `1.1.0` and `1.1.1`

<img width="1226" alt="Screenshot 2020-06-19 16 49 57" src="https://user-images.githubusercontent.com/2255993/85132121-5886f480-b262-11ea-859e-0a4087ea6d40.png">

```
$ yarn develop
$ gatsby develop -S
info setting up automatic SSL certificate (may require elevated permissions/sudo)

rm: cannot remove '/usr/local/share/ca-certificates/devcert.crt': No such file or directory
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/n/nss/libnss3-tools_3.35-2ubuntu2.7_amd64.deb  404  Not Found [IP: 52.165.132.12 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
error Failed to generate dev SSL certificate


  Error: Command failed: sudo apt install libnss3-tools
  WARNING: apt does not have a stable CLI interface. Use with caution in scripts  .
  E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/n/nss/libns  s3-tools_3.35-2ubuntu2.7_amd64.deb  404  Not Found [IP: 52.165.132.12 80]
  E: Unable to fetch some archives, maybe run apt-get update or try with --fix-m  issing?
  
  - utils.js:22 Object.run
    [poolotto-gatsby]/[devcert]/dist/utils.js:22:28
```

Our e2e cypress testing is setup to use certificates, and all tests failing, so we can't deploy to any of environments, at least it works locally, but how do you explain that to managers?

**Comment by Js-Brecht** [comment]
@JustFly1984 I think one way you could fix that is to install `libnss` prior to running `gatsby develop`.  That way you can tailor it to the environment it is running in.

**Comment by Js-Brecht** [comment]
@JustFly1984 try adding this to your action, before your `gatsby develop` command:

```yaml
- name: Update apt sources
  run: sudo apt-get update
- name: Install libnss3-tools
  run: sudo apt-get install -y libnss3-tools
```

**Comment by JustFly1984** [comment]
@Js-Brecht we have switched ubuntu to `macos-latest` in Github actions and reverted `devcert@1.1.0` back, so build pipeline is restored. 

1.1.1 does not work for `macos` with 'localhost' issue. Why is it trying to fetch something after yarn/npm install? Shouldn't everything required for module to run be inside the module?

**Comment by Js-Brecht** [comment]
`devcert` uses `certutil` for managing NSS DBs, and that's what comes with `libnss3-tools`.  Firefox uses NSS DBs, and Chrome does on Linux, too.  It would be nice to package all of that up, but there are no bindings for `libnss`.  As a result, `devcert` relies on the host machine having the library installed.

`libnss` is an open source library developed by Mozilla, so it's available for anybody to write bindings.  I've almost done it myself a few times, but I've got so much other work that is higher priority.

**Comment by JustFly1984** [comment]
@Js-Brecht is there any fix to 1.1.1?

**Comment by Js-Brecht** [comment]
#57 will fix it

**Comment by Primajin** [comment]
This issue resurfaced for me in `1.2.1` - `1.2.0` worked fine for me.
I can see it has a new dependency `is-valid-domain`?

**Comment by georgeHtmlBurger** [comment]
I also just did a fresh install using this Gatsby starter: https://github.com/gatsbyjs/gatsby-starter-wordpress-blog and first got issues with a self-signed certificate; once I tried to issue a cert through Gatsby I got that error: "Error: "localhost" is not a valid domain name."
